#!/usr/bin/env ruby

require 'json'
require 'open-uri'

blob=JSON.parse(URI.open('https://api.github.com/orgs/lojban/repos?type=all&per_page=500').read)

URLs=[]
blob.each { |x| URLs << x['clone_url'] }

backup_dir=ARGV.shift

if ! backup_dir || backup_dir.length < 5
  print "First argument must by the place to store the backups.\n"
  exit 1
end

URLs.each do |url|
  Dir.chdir backup_dir

  short=url.sub( %r{^.*/}, '' ).sub( %r{\.git$}, '' )

  puts "Stuff: #{url}, #{short}"

  if not Dir.exists?( short )
    puts %x{git clone #{url}}
  end

  Dir.chdir short

  puts %x{git fetch --all}
  puts %x{git pull}
  status=%x{git status}
  unless status =~ %r{nothing to commit, working tree clean}
    puts "!!!!!!! Status check for #{short} failed: #{status}"
  end
end

# Hints of how things worked in case this ever needs to be modified:
#
#2.0.0-p247 :002 > require 'json'
#
# => true
#
#2.0.0-p247 :003 > blob=JSON.parse(open('
#https://api.github.com/users/lojban/repos').read)
#
#Errno::ENOENT: No such file or directory -
#https://api.github.com/users/lojban/repos
#
#        from (irb):3:in `initialize'
#
#        from (irb):3:in `open'
#
#        from (irb):3
#
#        from /home/rlpowell/.rvm/rubies/ruby-2.0.0-p247/bin/irb:12:in
#`<main>'
#2.0.0-p247 :004 > blob=JSON.parse(open('
#https://api.github.com/users/lojban/repos').read) ; nil
#
#Errno::ENOENT: No such file or directory -
#https://api.github.com/users/lojban/repos
#
#        from (irb):4:in `initialize'
#
#        from (irb):4:in `open'
#
#        from (irb):4
#
#        from /home/rlpowell/.rvm/rubies/ruby-2.0.0-p247/bin/irb:12:in
#`<main>'
#2.0.0-p247 :005 > require 'open-uri'
#
# => true
#
#
#2.0.0-p247 :006 > blob=JSON.parse(open('
#https://api.github.com/users/lojban/repos').read) ; nil
#
# => nil
#
#2.0.0-p247 :007 > blob.each { |x| puts x['clone_url'] } ; nil
#
#
