#!/usr/bin/env ruby

require 'json'
require 'open-uri'

blob=JSON.parse(URI.open('https://api.github.com/orgs/lojban/repos?type=all&per_page=500').read)

URLs=[]
blob.each { |x| URLs << x['clone_url'] }

backup_dir=ARGV.shift
uid=ARGV.shift
gid=ARGV.shift

if ! backup_dir || backup_dir.length < 5
  print "First argument must by the place to store the backups.\n"
  exit 1
end

URLs.each do |url|
  # Make it owned by root so git won't complain
  puts %x{chown -R 0:0 #{backup_dir}}

  Dir.chdir backup_dir

  short=url.sub( %r{^.*/}, '' ).sub( %r{\.git$}, '' )

  puts "Stuff: #{url}, #{short}"

  if not Dir.exists?( short )
    puts %x{git clone #{url}}
  end

  Dir.chdir short

  puts %x{git fetch --all}
  puts %x{git pull}
  status=%x{git status}
  unless status =~ %r{nothing to commit, working tree clean}
    puts "!!!!!!! Status check for #{short} failed: #{status}"
  end

  # Put the ownership back
  puts %x{chown -R #{uid}:#{gid} #{backup_dir}}
end

puts "lobjan github backup complete"
