<%= "\n"*30 %>
<%= "# YOU ARE IN THE WRONG PLACE" %>
<%= "# YOU ARE IN THE WRONG PLACE use the ERB file" %>
<%= "# YOU ARE IN THE WRONG PLACE" %>

FROM fedora:34

# *************** WARNING
# DO NOT change the exim user's UID: Fedora exim wants to setuid to "93" specifically, by ID; changing the exim user will just cause confusion and heartache
#
# (This is the default for how exim is built, so it's not obvious that using non-Fedora exim would help, unless we want to build it ourselves.)
#
# To make everything work, the running user's UID on the host is mapped to UID 93 in the container.
#
# For further discussion see containers/exim/config
# *************** WARNING

RUN dnf -y install --best --allowerasing findutils curl vim-minimal less tzdata glibc-all-langpacks procps-ng psutils mailx swaks exim patch openssl hostname mhonarc && dnf clean all

COPY misc/exim-gen-cert.sh /usr/local/bin/exim-gen-cert.sh

COPY misc/aliases /etc/aliases

# This is all going to seem like a weird and very round-about way of
# doing it; why not just lay down the new conf file?  This is
# because as we update Fedora and/or Exim, the upstream conf file
# changes, and we are often very interested in those changes as they
# can represent new best practices or features, so this is basically
# a test for "did the upstream conf file change enough that we need
# to review it?", because if it did the patch will fail.
COPY misc/exim.conf.mine /etc/exim/
COPY misc/exim.conf.upstream /etc/exim/
RUN diff -u /etc/exim/exim.conf.mine /etc/exim/exim.conf.upstream > /etc/exim/exim.conf.patch
RUN cat /etc/exim/exim.conf.patch | patch -l /etc/exim/exim.conf

# Get all our logs to show up in docker output
RUN ln -sf /dev/stdout /var/log/exim/main.log && \
    ln -sf /dev/stdout /var/log/exim/reject.log && \
    ln -sf /dev/stderr /var/log/exim/panic.log

# MHonArc setup bits
COPY misc/indexerc_mhonarc /usr/local/etc/mhonarc/indexer.mrc
COPY misc/mhonarc_update.sh /usr/local/bin/mhonarc_update.sh

# DKIM setup bits
COPY misc/dkim.public /etc/exim/dkim.public
COPY misc/dkim.private /etc/exim/dkim.private
RUN chown exim:exim /etc/exim/dkim.*

ENV TZ America/Los_Angeles
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
