<%= "\n"*30 %>
<%= "# YOU ARE IN THE WRONG PLACE" %>
<%= "# YOU ARE IN THE WRONG PLACE use the ERB file" %>
<%= "# YOU ARE IN THE WRONG PLACE" %>

FROM fedora:34

# *************** WARNING
# DO NOT change the exim user's UID: Fedora exim wants to setuid to "93" specifically, by ID; changing the exim user will just cause confusion and heartache
#
# (This is the default for how exim is built, so it's not obvious that using non-Fedora exim would help, unless we want to build it ourselves.)
#
# For further discussion see containers/exim/config
# *************** WARNING

RUN dnf -y install --best --allowerasing findutils curl vim-minimal less tzdata glibc-all-langpacks procps-ng psutils mailx swaks patch spamassassin && dnf clean all

RUN for user in mail nobody ; \
do \
find / -xdev -user $user -print0 | xargs -r -0 chown 93 ; \
usermod -o -u 93 $user ; \
done

RUN for group in mail nobody ; \
do \
find / -xdev -group $group -print0 | xargs -r -0 chgrp 93 ; \
groupmod -o -g 93 $group ; \
done

RUN mkdir /.spamassassin 
RUN chown -R 93:93 /.spamassassin /etc/mail/spamassassin/

ENV TZ America/Los_Angeles
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
